### ISSUE TITLE
RSA: Read from PEM format

### ISSUE THREAD

**Issue by tinchodias** [pharo-contributions/Cryptography#11]
In master, this is the way to create a private key:

~~~
RSAPrivateKey p: int1 q: int2 dP: int3 dQ: int4 qInv: int5
~~~

It is usual to have the private key in a file with the pem format (i.e. starting with "-----BEGIN RSA PRIVATE KEY-----").

This issue could be extended to reading public keys. Additionally, it would be nice to support writing to pem format and not only reading.... But I prefer to focus in something specific, for the moment.

**Comment by tinchodias** [comment]
Update: There is a `RSAPrivateKeyFileReader`, but it raises error [here](https://github.com/pharo-contributions/Cryptography/blob/master/source/ASN1-Readers.package/RSAPrivateKeyFileReader.class/instance/initializeFromFileContents..st) because `#findAnySubStr:startingAt:` doesn't exist. 

There are some `#findSubstring:`* at `String`, so I'm trying to understand how to replace it.

**Comment by noha** [comment]
@tinchodias These are really good inputs Wouldn't it be possible that you do just a PR with it? That would be super awesome.

**Comment by tinchodias** [comment]
I'm sorry but I was frustrated and just made it work externally to Pharo, and abandoned this intent... we can close the issue.

**Comment by noha** [comment]
Ah too late and too less time. I could have extracted the pieces from my ASN.1 repo.
