### ISSUE TITLE
Undeclared references to FillInTheBlank

### ISSUE THREAD

**Issue by tinchodias** [pharo-contributions/Cryptography#12]
In Pharo7, it looks like the replacement of `FillInTheBlank` is `UIManager default`.

How should I contribute? create my fork and then a PR?

**Comment by noha** [comment]
If you have commit rights to contributions you can create a branch here and then do a pull request. If not forking and do a pull request works, too

**Comment by noha** [comment]
Usually it is always the easiest to fork make a branch in your fork and then open a pull request. But I added you as collaborator on this package so you can do it here

**Comment by tinchodias** [comment]
Thank you for adding me as collaborator. If Iget again an excuse to work on it I will fix it, but that's not now. Maybe we should close this issue.
