### ISSUE TITLE
1 long filename causes error in Win 10 loading 

### ISSUE THREAD

**Issue by sanjayminni** [pharo-contributions/Cryptography#15]
can the following filename be shortened, its causing a crash when loading in Win 10 (so a workaround has to be done just for this much)

filename:
cryptUIDlgSelectCertificateFromStore.winHandle.pwszTitle.pwszDisplayString.dwDontUseColumn.flags.reserved..st

location:
https://github.com/pharo-contributions/Cryptography/tree/master/source/Cryptography-MSCerts.package/Win32FFICertificateStore.class/instance

Probably this filename is autogenerated so a tweak could be attempted

**Comment by SabineMa** [comment]
There was a discussion on the mailing list for this topic:
http://forum.world.st/Voyage-td5088984i20.html

I was trying to convert the package to tonel. Took new pharo 7 image, load cryptograpy from github and then in iceberg I select "Extras->convert sources to tonel". 
I get this error ""'Method protocol ''crypto3.9compatibility'' for the method ''new'' in class ''ThirtyTwoBitRegister'' is inconsistent with the package name ''crypto3.9compatibility'''"

Would be nice if someone could help

**Comment by noha** [comment]
This done for two reasons. The package with the long filename has been deleted because it is dead. And I converted the source to tonel which should prevent that problem
